language: java
jdk:
   -openjdk15
addons:
  sonarcloud:
    organization: "ludovico99"
    token:
      secure: "b8c2723ef3fc8ec04fdf54343066a850a50af00b" # encrypted value of your token

script:
  - ant build
  - sonar-scanner
